const BOOKS_MODULES = Object.freeze({
  Items: ['id', 'item_name', 'sku', 'rate', 'purchase_rate', 'description', 'status'],
  'Price Lists': ['id', 'name', 'description', 'currency_code', 'status'],
  'Inventory Adjustments': ['id', 'date', 'reference_number', 'status', 'total_amount'],
  Customers: ['id', 'customer_name', 'email', 'phone', 'status', 'created_time'],
  Quotes: ['id', 'estimate_number', 'customer_name', 'status', 'total', 'date', 'expiry_date'],
  Estimates: ['id', 'estimate_number', 'customer_name', 'status', 'total', 'due_date'],
  'Retainer Invoices': ['id', 'retainer_invoice_number', 'customer_name', 'status', 'total', 'due_date'],
  'Sales Orders': ['id', 'salesorder_number', 'customer_name', 'status', 'total', 'created_time'],
  'Delivery Challans': ['id', 'deliverychallan_number', 'customer_name', 'status', 'total'],
  Invoices: ['id', 'invoice_number', 'customer_name', 'status', 'total', 'balance', 'due_date'],
  'Payments Received': ['id', 'payment_number', 'customer_name', 'amount', 'payment_date'],
  'Recurring Invoices': ['id', 'invoice_number', 'customer_name', 'status', 'total'],
  'Credit Notes': ['id', 'creditnote_number', 'customer_name', 'status', 'total'],
  Vendors: ['id', 'vendor_name', 'email', 'phone', 'status', 'created_time'],
  Expenses: ['id', 'expense_number', 'vendor_name', 'amount', 'expense_date'],
  'Recurring Expenses': ['id', 'expense_number', 'vendor_name', 'amount', 'status'],
  'Purchase Orders': ['id', 'purchaseorder_number', 'vendor_name', 'status', 'total'],
  Bills: ['id', 'bill_number', 'vendor_name', 'status', 'total', 'due_date'],
  'Payments Made': ['id', 'payment_number', 'vendor_name', 'amount', 'payment_date'],
  'Recurring Bills': ['id', 'bill_number', 'vendor_name', 'status', 'total'],
  'Vendor Credits': ['id', 'vendorcredit_number', 'vendor_name', 'status', 'total'],
  Projects: ['id', 'project_name', 'status', 'budget'],
  'Timesheet': ['id', 'employee_name', 'project_name', 'hours', 'date'],
  'Bank Accounts': ['id', 'account_name', 'account_number', 'bank_name', 'balance'],
  'Bank Transactions': ['id', 'transaction_id', 'account_name', 'amount', 'transaction_date'],
  'Manual Journals': ['id', 'journal_number', 'status', 'amount'],
  'Currency Adjustments': ['id', 'date', 'currency_code', 'adjustment_amount'],
  'Chart of Accounts': ['id', 'account_name', 'account_type', 'status'],
  Budgets: ['id', 'budget_name', 'period', 'amount'],
  Reports: ['id', 'report_name', 'generated_at'],
  Documents: ['id', 'document_name', 'document_type', 'created_time'],
  'Custom Modules': ['id', 'module_name', 'created_time']
});

const BOOKS_API_NAMES = Object.freeze({
  Items: 'items',
  'Price Lists': 'pricelists',
  'Inventory Adjustments': 'inventoryadjustments',
  Customers: 'contacts',
  Quotes: 'estimates',
  Estimates: 'estimates',
  'Retainer Invoices': 'retainerinvoices',
  'Sales Orders': 'salesorders',
  'Delivery Challans': 'deliverychallans',
  Invoices: 'invoices',
  'Payments Received': 'customerpayments',
  'Recurring Invoices': 'recurringinvoices',
  'Credit Notes': 'creditnotes',
  Vendors: 'contacts',
  Expenses: 'expenses',
  'Recurring Expenses': 'recurringexpenses',
  'Purchase Orders': 'purchaseorders',
  Bills: 'bills',
  'Payments Made': 'vendorpayments',
  'Recurring Bills': 'recurringbills',
  'Vendor Credits': 'vendorcredits',
  Projects: 'projects',
  'Timesheet': 'timeentries',
  'Bank Accounts': 'bankaccounts',
  'Bank Transactions': 'banktransactions',
  'Manual Journals': 'journals',
  'Currency Adjustments': 'currencyadjustments',
  'Chart of Accounts': 'chartofaccounts',
  Budgets: 'budgets',
  Reports: 'reports',
  Documents: 'documents'
});

module.exports = { BOOKS_MODULES, BOOKS_API_NAMES };
